<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{bd1d28dd-26f5-431c-a0e2-298491b67956}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSystemController : FB_SystemController;
	fbTestAlarmManager : TEST_FB_AlarmManager();
	fbBatteryManager   : TEST_FB_BatteryManager();
	fbEnergySources    : TEST_FB_EnergySources();
	fbGridManager	   : TEST_FB_GridManager();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();

//fbSystemController.ExecuteCycle();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="39" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>